services:
  it-workstation:
    build: ./it-workstation
    container_name: it-workstation
    networks:
      - it-net

  dmz-webserver:
    build: ./dmz-webserver
    container_name: dmz-webserver
    networks:
      - it-net
      - dmz-net

  scada-server:
    build: ./scada-server
    container_name: scada-server
    networks:
      - dmz-net
      - ot-net

  hmi-client:
    build: ./hmi-client
    container_name: hmi-client
    networks:
      - ot-net

  logger:
    build: ./logger
    container_name: logger
    networks:
      - it-net
      - dmz-net
      - ot-net

networks:
  it-net:
    driver: bridge
  dmz-net:
    driver: bridge
  ot-net:
    driver: bridge
