version: '3.8'
services:
  it_workstation:
    build: ./it_workstation
    ports:
      - "2222:22"
    networks:
      - corporate_net
      - ot_net
  scada_server:
    build: ./scada_server
    networks:
      - ot_net
networks:
  corporate_net:
  ot_net:
    internal: true
